---
- name: Add Docker Repository
  yum_repository:
    name: docker-ce
    description: docker-ce-repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable

- name: Update yum and install docker-ce
  yum:
    name: docker-ce-18.09.9-3.el7
    state: absent
    update_cache: yes

- name: Lock docker version
  shell: | 
    yum versionlock docker-ce-18.09.9-3.el7
